# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/passion/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries

# All the blobs necessary for passion
PRODUCT_COPY_FILES += \
    device/acer/liquid/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
   device/acer/liquid/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
   device/acer/liquid/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
   device/acer/liquid/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \

